#%RAML 1.0
title: cabinet
version: "0.0.0.1"
baseUri: cabinet/
/cabinet: 
    displayName: Cabinet Resource
    description: Cabinet Resource
    /auth: 
        displayName: Auth Resource
        description: Auth Resource
        post: 
            description: |
                <p>
                 POST /cabinet/auth
                 Content-Type: application/json
                 Cache-Control: no-cache
                 
                 Пример ожидаемых параметров
                 {</p><ul>
                 <li>"username":"aa71-2464877",</li>
                 <li>"password":"i_pswd"</li>
                 </ul><p>}</p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:security:JwtAuthenticationRequest",
                          "properties" : {
                            "username" : {
                              "type" : "string"
                            },
                            "password" : {
                              "type" : "string"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        <p> пример удачного ответа
                         {</p><ui>
                         <li>  "state": 1,</li>
                         <li>  "errMessage": "",</li>
                         <li>  "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYTcxLTI0NjQ4NzciLCJhdWQiOiJ3ZWIiLCJleHAiOjE1MjE3MDQ2NTMs
                         ImlhdCI6MTUyMTA5OTg1MywianRpIjoiNjQwNjk0In0.89StR1DqD4-JgP5ezfxHM5ksxsoysILh3qD3jkDyGcjDPJFcYvLCFv-RZYtGSD
                         959O2qMinfKPcY4LeQcs7Fbg"</li>
                         </ui><p>}</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:AuthToken",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "token" : {
                                      "type" : "string"
                                    }
                                  }
                                }
    /refresh: 
        displayName: Refresh Resource
        description: Refresh Resource
        get: 
            description: refreshAndGetAuthenticationToken
            responses: 
                "200": 
                    description: Successful Response
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "any"
                                }
    /sendsms: 
        displayName: Sendsms Resource
        description: Sendsms Resource
        post: 
            description: |
                <p>
                 Отправка кода подтверждения клиенту посредством отправки СМС
                 POST /cabinet/sendsms HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWGqwCFG6k8E7nzLTFtFp_4Z4kq6DD79Alkg<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 Postman-Token: abe178fb-a53d-8ab9-e5b0-27f02a2b6996<br/>
                 </p>
                 <p>
                 Пример ожидаемых параметров<br/>
                 { <br/>
                 "tell":"998998494533"<br/>
                 }</p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:rest:SMSRequest",
                          "properties" : {
                            "tell" : {
                              "type" : "string"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа
                         <p>{<br/>
                         "state": 1,<br/>
                         "errMessage": ""<br/>
                         }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:RestResponce",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    }
                                  }
                                }
    /dvoservices: 
        displayName: Dvoservices Resource
        description: Dvoservices Resource
        post: 
            description: |
                <p>
                 Активизация деактивизация услуг ДВО<br/>
                 POST /cabinet/dvoservices HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiORWGqwCFG6k8E7nzLTFtFp_4Z4kq6DD79Alkg<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 Postman-Token: 9e0684f4-f325-58d5-09d3-a845de89a277<br/>
                 </p>
                 <ui>
                 <li>"cmd":1, тип команды возможные значения CMD_NATIONAL_NET_ON(1),CMD_NATIONAL_NET_OFF(2),CMD_TURBO_SERVICE_ON(3),CMD_TURBO_SERVICE_OFF(4)</li>
                 <li>"serviceID":0 национальная сеть, в остальных случаях отправляется идентификатор выбранной услуги</li>
                 <li>"serviceStartDate":"07.03.2018 11:10:1542" .. Дата начала услуги не обязательный параметр</li>
                 <li>"serviceEndDate":"07.03.2018 11:10:1542" .. Дата окончания услуги не обязательный параметр</li>
                 <li>"smscode":"4545556" .. код подтверждения </li>
                 </ui>
                 
                 Пример ожидаемых параметров<br/>
                 <p>
                 { <br/>
                 "cmd":1,<br/>
                 "serviceID":0,<br/>
                 }</p>
                 <p>
                 { <br/>
                 "cmd":2,<br/>
                 "serviceID":0<br/>
                 }</p>
                 <p>
                 { <br/>
                 "cmd":3,<br/>
                 "serviceID":45215,<br/>
                 "smscode":"456789"
                 }</p>
                 <p>
                 { <br/>
                 "cmd":3,<br/>
                 "serviceID":0,<br/>
                 "smscode":"456795",<br/>
                 "serviceStartDate":"07.03.2018 11:10:1542",<br/>
                 "serviceEndDate":"07.03.2018 11:10:1542"<br/>
                 }</p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:rest:ServiceDVO_Request",
                          "properties" : {
                            "cmd" : {
                              "type" : "integer"
                            },
                            "serviceID" : {
                              "type" : "integer"
                            },
                            "serviceStartDate" : {
                              "type" : "string",
                              "format" : "date-time"
                            },
                            "serviceEndDate" : {
                              "type" : "string",
                              "format" : "date-time"
                            },
                            "smscode" : {
                              "type" : "string"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа<br/>
                         <br/>
                         {<br/>
                         "state": 1,<br/>
                         "errMessage": ""<br/>
                         }
                         </p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:RestResponce",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    }
                                  }
                                }
    /traff: 
        displayName: Traff Resource
        description: Traff Resource
        post: 
            description: |
                <p>
                 Вывод в табличном предстовлении потраченного трафика клиента<br/>
                 запрос с<br/>
                 POST /cabinet/traff <br/>
                 X-Access-token: Bearer eyJhbGciOiJIUzUxMiJX56ReW9a7HdswOuIK5V9RxTFG4Ccg<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 <br/>
                 Пример ожидаемых параметров<br/>
                 { </p>
                 <ul><li>"date_beg":"01.01.2018",</li>
                 <li>"date_end":"20.03.2018"</li></ul>
                 <p>  } </p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:rest:PeriodDateRequest",
                          "properties" : {
                            "date_beg" : {
                              "type" : "string"
                            },
                            "date_end" : {
                              "type" : "string"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        пример удачного ответа
                         <p> {
                               "state": 1,<br/>
                               "errMessage": "",<br/>
                               "rows": [<br/>
                                     {<br/>
                              </p>
                                     <ul><li>    "VOL_USED_INET": "      .00",     .. Использованная внешка</li>
                                        <li>"VOL_COST_INET": "      .00",     .. Начисленная стоимость (сверхлимит)</li>
                                        <li> "ORDERED": "1",                   .. для сортировки</li>
                                        <li> "VOL_USED_TASX": "    81.00",     .. Использованно tasix</li>
                                        <li> "INTERVAL_TIME": "16:00-17:00",   .. период времени</li>
                                        <li> "SERVISE_NAME": "Life NEW-1",     .. название услуги</li>
                                        <li> "DAY_DATE": "07.03.2018",         .. день начисления</li>
                                        <li> "MAC_ADDRESS": "6466.b38a.6f38"   .. мак адресс с которого пользовались
                            </li></ul>
                            <p>
                                     }<br/>
                                  ]<br/>
                               }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:SubscrTrafficResponce",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "rows" : {
                                      "type" : "array",
                                      "items" : {
                                        "type" : "object",
                                        "id" : "urn:jsonschema:ks:api:pojos:TrafficItem",
                                        "properties" : {
                                          "day_date" : {
                                            "type" : "string"
                                          },
                                          "interval_time" : {
                                            "type" : "string"
                                          },
                                          "service_name" : {
                                            "type" : "string"
                                          },
                                          "mac_address" : {
                                            "type" : "string"
                                          },
                                          "vol_used_inet" : {
                                            "type" : "number"
                                          },
                                          "vol_used_tasix" : {
                                            "type" : "number"
                                          },
                                          "vol_cost_inet" : {
                                            "type" : "number"
                                          },
                                          "tas_ix" : {
                                            "type" : "number"
                                          },
                                          "ordered" : {
                                            "type" : "integer"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
    /changePass: 
        displayName: ChangePass Resource
        description: ChangePass Resource
        post: 
            description: |
                <p>
                 Смена пароля абонента<br/>
                 <br/>
                 <br/>
                 POST /cabinet/changePass HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciOi_FCPJnsRrzLjEFYiIzmar1_tk-8YnL-jLZGbhSrQY1yzsfkCz175soRBQE-4jg<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 <br/>
                 Пример ожидаемых параметров<br/>
                 { </p>
                 <ul>
                 <li>  "curPass":"i_pswd",</li>
                 <li>  "newPass":"i_pswd"</li>
                 </ul>
                 <p>  }</p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:rest:ChangePassRequest",
                          "properties" : {
                            "curPass" : {
                              "type" : "string"
                            },
                            "newPass" : {
                              "type" : "string"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        <p> пример удачного ответа
                         {</p><ul>
                         <li> "state": 1,</li>
                         <li> "errMessage": "Действие выполнено успешно !",</li>
                         <li> "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIibpu1GB3XwgC39CinrTOuoTrbMbEw46YFvjw"   ..Новый токен</li>
                         </ul></p> }
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:AuthToken",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "token" : {
                                      "type" : "string"
                                    }
                                  }
                                }
    /subscriber: 
        displayName: Subscriber Resource
        description: Subscriber Resource
        post: 
            description: |
                <p>
                 Отображение данных о клиенте<br/>
                 запрос с<br/>
                 POST /cabinet/subscriber HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYTcxLTI0NzIzsfkCz175soRBQE-4jg<br/>
                 Content-Type: application/json<br/>
                 в параметре Bearer отправляется токен авторизации<br/>
            responses: 
                "200": 
                    description: |
                        пример удачного ответа
                         {
                         </p>
                         <ul><li> "state": 1,                               ..статус запроса  <> 1 тогда ошибка</li>
                         <li>"errMessage": "",                         ..при возникновении ошибки текст сообщения</li>
                         <li>"fio": "Аширов Сирожиддин Солих Угли",    ..Фамилия имя отчество абонента</li>
                         <li>"user_ip": null,                          ..выводится при наличии статичный IP адрес</li>
                         <li>"from": " Учтепа Тобрик  42 ",            ..адрес абонента</li>
                         <li>"login": "aa71-2472047",                  ..логин абонента</li>
                         <li>"tariff_name": "Life NEW-1",              ..название тарифа</li>
                         <li>"traffic_balance": 36292.5,               ..лимит трафика</li>
                         <li>"monthly_payment": 60483.87,              ..ежемесячные разовые платежи абонента(суммируется оплата за месяц, за дополнительные услуги)</li>
                         <li>"current_balance": -60483.87,             ..текущий баланс</li>
                         <li>"inet_tariff_capacity": 75000,            ..стоимость услуги по тарифу</li>
                         <li>"traffic_world": 7,                       ..сколько израсходованно внешки</li>
                         <li>"traffic_tasix": 11370,                   ..сколько израсходованно tasix</li>
                         <li>"balance_id": 399092,                     ..номер счета</li>
                         <li>"user_status": 1,                         ..статус пользователя 1 активный</li>
                         <li>"tariff_id": 10362,                       ..идентификатор тарифа</li>
                         <li>"pass_state": 1                           ..статус пароля 1 постоянный, 0 надо менять
                         </li></ul>
                         <p>}</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:Subscriber",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "fio" : {
                                      "type" : "string"
                                    },
                                    "user_ip" : {
                                      "type" : "string"
                                    },
                                    "from" : {
                                      "type" : "string"
                                    },
                                    "login" : {
                                      "type" : "string"
                                    },
                                    "tariff_name" : {
                                      "type" : "string"
                                    },
                                    "traffic_balance" : {
                                      "type" : "number"
                                    },
                                    "monthly_payment" : {
                                      "type" : "number"
                                    },
                                    "current_balance" : {
                                      "type" : "number"
                                    },
                                    "inet_tariff_capacity" : {
                                      "type" : "number"
                                    },
                                    "tasix_tariff_capacity" : {
                                      "type" : "number"
                                    },
                                    "traffic_world" : {
                                      "type" : "integer"
                                    },
                                    "traffic_tasix" : {
                                      "type" : "integer"
                                    },
                                    "balance_id" : {
                                      "type" : "integer"
                                    },
                                    "user_status" : {
                                      "type" : "integer"
                                    },
                                    "tariff_id" : {
                                      "type" : "integer"
                                    },
                                    "pass_state" : {
                                      "type" : "integer"
                                    }
                                  }
                                }
    /payments: 
        displayName: Payments Resource
        description: Payments Resource
        post: 
            description: |
                <p>
                 платежи за указанный период<br/>
                 <br/>
                 POST /cabinet/payments HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciORg7erx89U8tDRCDyjKMv-C4ayvTiX9A56p1DGU56Stx7TRoJFD7EKNQInc5Q<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 <br/>
                 Пример ожидаемых параметров<br/>
                 {</p><ul>
                 <li>  "date_beg":"01.01.2018",</li>
                 <li>  "date_end":"14.03.2018"</li>
                 </ul><p>}</p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:rest:PeriodDateRequest",
                          "properties" : {
                            "date_beg" : {
                              "type" : "string"
                            },
                            "date_end" : {
                              "type" : "string"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа
                         {<p>
                         "state": 1,
                         "errMessage": "",
                         "items": [
                         {</p>
                         <ul>
                         <li>           "REGIS_DATE": "14.03.2018",   ..дата платежа</li>
                         <li>           "EMP_NAME": "Admin",          ..сотрудник принявший платеж</li>
                         <li>           "ACC_ID": "80930",            ..на какой счет</li>
                         <li>           "TYPE_ID": "4",               ..идентификатор типа</li>
                         <li>           "ID_": "989711",              ..идентификатор платежа</li>
                         <li>           "REGIS_N": "13812",           ..регистрационный номер</li>
                         <li>           "AMOUNT_": "80645,16",        ..сумма платежа</li>
                         <li>           "TYPE_NAME": "Терминал",      ..тип оплаты</li>
                         </ul>
                         <p>       }
                         ]
                         }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:PaymentsList",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "items" : {
                                      "type" : "array",
                                      "items" : {
                                        "type" : "object",
                                        "id" : "urn:jsonschema:ks:api:pojos:Payment",
                                        "properties" : {
                                          "id_" : {
                                            "type" : "integer"
                                          },
                                          "acc_id" : {
                                            "type" : "integer"
                                          },
                                          "regis_n" : {
                                            "type" : "integer"
                                          },
                                          "type_id" : {
                                            "type" : "integer"
                                          },
                                          "amount_" : {
                                            "type" : "number"
                                          },
                                          "regis_date" : {
                                            "type" : "string"
                                          },
                                          "emp_name" : {
                                            "type" : "string"
                                          },
                                          "type_name" : {
                                            "type" : "string"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
    /changeTariff: 
        displayName: ChangeTariff Resource
        description: ChangeTariff Resource
        post: 
            description: |
                <p>
                 Смена тарифного плана<br/>
                 POST /cabinet/changeTariff HTTP/1.1<br/>
                 Host: 127.0.0.1:8080<br/>
                 X-Access-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrzLjEFYiIzmar1_tk-8YnL-jLZGbhSrQY1yzsfkCz175soRBQE-4jg<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 Postman-Token: 306b8537-3a48-30f2-6992-f24edbf2a85f<br/>
                 <br/>
                 Пример ожидаемых параметров<br/>
                 <br/>
                 {</p>
                 <ul>
                 <li>  "curTId":10362,  ..идентификатор текущего сервиса </li>
                 <li>  "newTid":10359   ..идентификатор сервиса на который планируется перейти </li>
                 </ul>
                 <p>   }<p>
            body: 
                application/json: 
                    schema: |
                        {
                          "type" : "object",
                          "id" : "urn:jsonschema:ks:api:rest:ChangeTariffRequest",
                          "properties" : {
                            "curTId" : {
                              "type" : "integer"
                            },
                            "newTid" : {
                              "type" : "integer"
                            }
                          }
                        }
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа<br/>
                         {</p><ul>
                         <li>   "state": 1</li>
                         <li>   "errMessage": "Success"</li>
                         </ul><p> }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:RestResponce",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    }
                                  }
                                }
    /tarifs: 
        displayName: Tarifs Resource
        description: Tarifs Resource
        post: 
            description: |
                <p>
                 Вывод сгруппированого списка всех активных тарифов<br/>
                 запрос с<br/>
                 POST /cabinet/tarifs<br/>
                 X-Access-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjLZGbhSrQY1yzsfkCz175soRBQE-4jg<br/>
                 Content-Type: application/json<br/>
                 в параметре Bearer отправляется токен авторизации<br/>
                 </p>
            responses: 
                "200": 
                    description: |
                        </p>
                         <p>
                         пример удачного ответа
                         {</p>
                         <ul>
                         <li>"state": 1,                          ..request state  <> 1</li>
                         <li>"errMessage": "",                    ..при возникновении ошибки текст сообщения</li>
                         <li>"tarrif_group": [{                   ..коллекция тарифных групп</li>
                         <li>  "name": "Active NEW",              ..название группы</li>
                         <li>  "items": [{                        ..group childrens</li>
                         <li>     "t_id": 10359,                  ..идентификатор тарифа</li>
                         <li>     "inet_traffic": 12500,          ..Включенный лимит внешнего трафика, Мб</li>
                         <li>     "t_ammount": 55000,             ..Абонентская плата, сум</li>
                         <li>     "daily_amount": 0,              ..Стоимость 1 МБ сверх лимита днем, сум</li>
                         <li>     "nightly_ammount": 0,           ..Стоимость 1 МБ сверх лимита ночью, сум</li>
                         <li>     "t_name": "Active NEW-2",       ..название тарифа</li>
                         <li>     "g_name": "Active NEW",         ..название группы</li>
                         <li>     "inet_speed": "2048 KBIT_S",    ..скорость доступа внешка</li>
                         <li>     "tasx_speed": "2048 KBIT_S",    ..скорость доступа tasix</li>
                         <li>     "daily_period": "0-0",          ..продолжительность дневного периода</li>
                         <li>     "nightly_period": "0-0"         ..продолжительность ночного периода</li>
                         </ul>
                         <p> }]<br/>
                         },<br/>
                         {<br/>
                         		{<br/>
                         "name": "Life Plus",<br/>
                         "items": [{<br/>
                         "t_id": 10291,<br/>
                         "inet_traffic": null,<br/>
                         "t_ammount": 150000,<br/>
                         "daily_amount": 0,<br/>
                         "nightly_ammount": 0,<br/>
                         "t_name": "Life plus-1",<br/>
                         "g_name": "Life Plus",<br/>
                         "inet_speed": " ",<br/>
                         "tasx_speed": "2048 KBIT_S",<br/>
                         "daily_period": "0-0",<br/>
                         "nightly_period": "0-0"<br/>
                         },<br/>
                         {<br/>
                         "t_id": 10292,<br/>
                         "inet_traffic": null,<br/>
                         "t_ammount": 200000,<br/>
                         "daily_amount": 0,<br/>
                         "nightly_ammount": 0,<br/>
                         "t_name": "Life plus-2",<br/>
                         "g_name": "Life Plus",<br/>
                         "inet_speed": " ",<br/>
                         "tasx_speed": "4096 KBIT_S",<br/>
                         "daily_period": "0-0",<br/>
                         "nightly_period": "0-0"<br/>
                         }<br/>
                         ]<br/>
                         }<br/>
                         }<br/>
                         ]<br/>
                         }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:TariffListGroupResponce",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "tarrif_group" : {
                                      "type" : "array",
                                      "items" : {
                                        "type" : "object",
                                        "id" : "urn:jsonschema:ks:api:pojos:TariffGroup",
                                        "properties" : {
                                          "name" : {
                                            "type" : "string"
                                          },
                                          "items" : {
                                            "type" : "array",
                                            "items" : {
                                              "type" : "object",
                                              "id" : "urn:jsonschema:ks:api:pojos:Tariff",
                                              "properties" : {
                                                "t_id" : {
                                                  "type" : "integer"
                                                },
                                                "inet_traffic" : {
                                                  "type" : "integer"
                                                },
                                                "t_ammount" : {
                                                  "type" : "number"
                                                },
                                                "daily_amount" : {
                                                  "type" : "number"
                                                },
                                                "nightly_ammount" : {
                                                  "type" : "number"
                                                },
                                                "t_name" : {
                                                  "type" : "string"
                                                },
                                                "g_name" : {
                                                  "type" : "string"
                                                },
                                                "inet_speed" : {
                                                  "type" : "string"
                                                },
                                                "tasx_speed" : {
                                                  "type" : "string"
                                                },
                                                "daily_period" : {
                                                  "type" : "string"
                                                },
                                                "nightly_period" : {
                                                  "type" : "string"
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
    /tariffHist: 
        displayName: TariffHist Resource
        description: TariffHist Resource
        post: 
            description: |
                <p>
                 История тарифов<br/>
                 <br/>
                 POST /cabinet/tariffHist HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbiIzmar1_tk-8YnL-jLZGbhSrQY1yzsfkCz175soRBQE-4jg<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 </p>
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа<br/>
                         {<br/>
                         "state": 1,<br/>
                         "errMessage": "",<br/>
                         "items": [<br/>
                         {</p>
                         <ul>
                         <li>             "service_name": "Life NEW-1",    ..Название сервиса</li>
                         <li>             "state_name": "Актив",           ..Статус</li>
                         <li>             "state": 1,                      ..идентификатор статуса</li>
                         <li>             "cmd_send_date": 1520418380000,  ..дата подачи заявки на изменение в милисекундах</li>
                         <li>             "tf_date_beg": 1520413503000,    ..дата начала</li>
                         <li>             "tf_date_end": null              ..дата окончания </li>
                         <ul>
                         <p>         },<br/>
                         ]<br/>
                         }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:HistoryList",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "items" : {
                                      "type" : "array",
                                      "items" : {
                                        "type" : "object",
                                        "id" : "urn:jsonschema:ks:api:pojos:HistoryItem",
                                        "properties" : {
                                          "service_name" : {
                                            "type" : "string"
                                          },
                                          "state_name" : {
                                            "type" : "string"
                                          },
                                          "state" : {
                                            "type" : "integer"
                                          },
                                          "cmd_send_date" : {
                                            "type" : "integer",
                                            "format" : "utc-millisec"
                                          },
                                          "tf_date_beg" : {
                                            "type" : "integer",
                                            "format" : "utc-millisec"
                                          },
                                          "tf_date_end" : {
                                            "type" : "integer",
                                            "format" : "utc-millisec"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
    /news: 
        displayName: News Resource
        description: News Resource
        post: 
            description: |
                <p>
                 Новости компании
                 POST /cabinet/news HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciOIpdCpUZYIXBWaNkd_zjdbckmpWmf7gzP_dKeHBDrhV70RPqA<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 Postman-Token: dfb32c87-1179-2a74-a068-ff6d855c9ae5<br/>
                 </p>
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа
                         {<p>
                         "state": 1,
                         "errMessage": "",
                         "news": [
                         {</p>
                         <ul>
                         <li>          "state": "ERROR",</li>
                         <li>          "tytle": "Системное сообщение",</li>
                         <li>          "message": "Ошибка привязки к порту.
                         Была попытка подключения  вашим логином
                         с неверного порта 20.11.2017 11:10:2017 "</li>
                         <ul> <p>
                         }
                         ]
                         }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:CabinetNews",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "news" : {
                                      "type" : "array",
                                      "items" : {
                                        "type" : "object",
                                        "id" : "urn:jsonschema:ks:api:pojos:Message",
                                        "properties" : {
                                          "state" : {
                                            "type" : "string"
                                          },
                                          "tytle" : {
                                            "type" : "string"
                                          },
                                          "message" : {
                                            "type" : "string"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
    /notifications: 
        displayName: Notifications Resource
        description: Notifications Resource
        post: 
            description: |
                <p>
                 Оповещение абонента
                 POST /cabinet/notifications HTTP/1.1<br/>
                 X-Access-token: Bearer eyJhbGciOIpdCpUZYIXBWaNkd_zjdbckmpWmf7gzP_dKeHBDrhV70RPqA<br/>
                 Content-Type: application/json<br/>
                 Cache-Control: no-cache<br/>
                 Postman-Token: dfb32c87-1179-2a74-a068-ff6d855c9ae5<br/>
                 </p>
            responses: 
                "200": 
                    description: |
                        <p>
                         пример удачного ответа
                         {<p>
                         "state": 1,
                         "errMessage": "",
                         "news": [
                         {</p>
                         <ul>
                         <li>          "state": "ERROR",</li>
                         <li>          "tytle": "Системное сообщение",</li>
                         <li>          "message": "Ошибка привязки к порту.
                         Была попытка подключения  вашим логином
                         с неверного порта 20.11.2017 11:10:2017 "</li>
                         <ul> <p>
                         }
                         ]
                         }</p>
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "object",
                                  "id" : "urn:jsonschema:ks:api:pojos:CabinetNews",
                                  "properties" : {
                                    "state" : {
                                      "type" : "integer"
                                    },
                                    "errMessage" : {
                                      "type" : "string"
                                    },
                                    "news" : {
                                      "type" : "array",
                                      "items" : {
                                        "type" : "object",
                                        "id" : "urn:jsonschema:ks:api:pojos:Message",
                                        "properties" : {
                                          "state" : {
                                            "type" : "string"
                                          },
                                          "tytle" : {
                                            "type" : "string"
                                          },
                                          "message" : {
                                            "type" : "string"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
